### ISSUE TITLE
Script exports, convert methods names to lowercase

### ISSUE THREAD

**Issue by hduarte** [frida/frida-python#104]
If one defines a method using upper case characters inside an rpc.exports definition, it won't be possible to call it because the upon call it gets converted to lowercase. Lets use this code as an example: https://github.com/frida/frida-python/blob/master/examples/rpc.py

By changing the method name to Hello instead of hello (capital H is the difference) and upon calling we change it to Hello also instead of hello, and an exception is thrown indicating that the method hello (yes lower case h) doesn't exist.

**Comment by hduarte** [comment]
Ok found the explanation for such behaviour inside https://github.com/frida/frida-python/blob/master/src/frida/core.py

The behaviour is as follows:

- one can declare functions using for example camel case firstSecondeThird inside the rpc.exports object
- upon call one must set the uppercase char in lowercase and insert an underscore between words (see function _to_camel_case inside core.py), so to call the method above one would use first_second_third() and not firstSecondThird() as declared inside the rpc.exports object.

**Comment by oleavr** [comment]
I should add that the intention here is to be able to follow the camelCase-convention followed in idiomatic JavaScript, and still be able to follow PEP 8 on the Python side, i.e. `sayHello` on the JS side becomes `say_hello` on the Python side. Similarly a C#/.NET binding would convert it into `SayHello`. Cheers!
