### ISSUE TITLE
Hardcoded python paths in Windows

### ISSUE THREAD

**Issue by pedrib** [frida/frida-python#11]
Hi,

I'm getting build errors due to the hardcoding of python paths in:
frida-python\frida-python27.vcxproj
frida-python\frida-python33.vcxproj

The paths seem to be hardcoded to "C:\Program Files (x86)\PythonXX\". Change these to the correct paths (in my case C:\code\PythonXX) makes it build again.

**Comment by oleavr** [comment]
Considering this fixed.
