### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by agustingianni** [frida/frida-python#125]
While using the RPC interface from python, I'm having issues sending raw data to the JS script. If the raw data (I'm using a string to represent it) contains a value that cannot be represented in unicode, it throws an exception.

`UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 0: invalid start byte`

https://github.com/frida/frida-python/blob/dbb0704f2c4143e4e55eb1ff814c8d72c3dead3d/src/frida/core.py#L306

**Comment by oleavr** [comment]
This is a limitation of our current RPC interface.

We currently build it on top of the `recv()` and `send()` primitives, so the entire RPC implementation is pure JavaScript. You can find it [here](https://github.com/frida/frida-gum/blob/641a845ed1f55a4379d3d2e04ed9c1387f850ede/bindings/gumjs/runtime/message-dispatcher.js#L32-L72), and on the Python side it is implemented [here](https://github.com/frida/frida-python/blob/dbb0704f2c4143e4e55eb1ff814c8d72c3dead3d/src/frida/core.py#L327-L370). If you're interested it would be great to improve our implementation to support binary data arguments (we currently make use of it for the return value, if you return an `ArrayBuffer` from the JS side, but not yet for arguments).

Using the optional out-of-band binary data passed to the second argument of `post()` (on the Python side), and received in the second argument to the `recv()` callback (on the JS side), we could put all the binary data there as one contiguous blob, and just reference it from the arguments. The JS side would then recognize the magic markers in the arguments and know that it should unpack each from the binary blob next to the message.

**Comment by oleavr** [comment]
As a workaround you could always pass an array of numbers between 0 and 255, which e.g. `Memory.writeByteArray()` supports in addition to `ArrayBuffer`.

**Comment by agustingianni** [comment]
Oh, I see. Anyways thanks, passing an array works fine here.
Cheers!
