### ISSUE TITLE
segfault when running in ipython

### ISSUE THREAD

**Issue by fabianfreyer** [frida/frida-python#13]
On OS X, the following scripts when run in ipython, but not when run in python:
    import frida
    p = frida.attach("cat")

The backtrace is as follows:
        Crashed Thread:  0  Dispatch queue: com.apple.main-thread

        Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
        Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000

        VM Regions Near 0:
        -->
            __TEXT                 0000000102d4c000-0000000102d4e000 [    8K] r-x/rwx SM=COW  /usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

        Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
        0   ???                                 000000000000000000 0 + 0
        1   org.python.python                   0x00000001060f737d PyEval_GetGlobals + 23
        2   org.python.python                   0x0000000106105ea5 PyImport_Import + 131
        3   org.python.python                   0x0000000106104687 PyImport_ImportModule + 31
        4   _frida.so                           0x0000000104d72b07 init_frida + 23
        5   org.python.python                   0x0000000102dedfbe _PyImport_LoadDynamicModule + 140
        6   org.python.python                   0x0000000102decc82 imp_load_dynamic + 112
        7   org.python.python                   0x0000000102dd7c4b PyEval_EvalFrameEx + 7751
        8   org.python.python                   0x0000000102ddc2d1 fast_function + 192
        9   org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        10  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        11  org.python.python                   0x0000000102dd5625 PyEval_EvalCode + 54
        12  org.python.python                   0x0000000102dea539 PyImport_ExecCodeModuleEx + 236
        13  org.python.python                   0x0000000102e194ef zipimporter_load_module + 417
        14  org.python.python                   0x0000000102d5c9ef PyObject_Call + 99
        15  org.python.python                   0x0000000102d5cb80 call_function_tail + 72
        16  org.python.python                   0x0000000102d5cd98 PyObject_CallMethod + 259
        17  org.python.python                   0x0000000102dedccb import_submodule + 274
        18  org.python.python                   0x0000000102ded8d6 load_next + 345
        19  org.python.python                   0x0000000102deb84c PyImport_ImportModuleLevel + 589
        20  org.python.python                   0x0000000102dd121b builtin___import__ + 135
        21  org.python.python                   0x0000000102d5c9ef PyObject_Call + 99
        22  org.python.python                   0x0000000102ddba77 PyEval_CallObjectWithKeywords + 93
        23  org.python.python                   0x0000000102dd8292 PyEval_EvalFrameEx + 9358
        24  org.python.python                   0x0000000102ddc2d1 fast_function + 192
        25  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        26  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        27  org.python.python                   0x0000000102ddc338 fast_function + 295
        28  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        29  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        30  org.python.python                   0x0000000102dd9e4a PyEval_EvalFrameEx + 16454
        31  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        32  org.python.python                   0x0000000102ddc338 fast_function + 295
        33  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        34  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        35  org.python.python                   0x0000000102ddc338 fast_function + 295
        36  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        37  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        38  org.python.python                   0x0000000102ddc338 fast_function + 295
        39  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        40  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        41  org.python.python                   0x0000000102ddc338 fast_function + 295
        42  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        43  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        44  org.python.python                   0x0000000102ddc338 fast_function + 295
        45  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        46  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        47  org.python.python                   0x0000000102ddc338 fast_function + 295
        48  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        49  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        50  org.python.python                   0x0000000102d7a91f function_call + 349
        51  org.python.python                   0x0000000102d5c9ef PyObject_Call + 99
        52  org.python.python                   0x0000000102dd8ae9 PyEval_EvalFrameEx + 11493
        53  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        54  org.python.python                   0x0000000102ddc338 fast_function + 295
        55  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        56  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        57  org.python.python                   0x0000000102dd5625 PyEval_EvalCode + 54
        58  org.python.python                   0x0000000102df54ba run_mod + 53
        59  org.python.python                   0x0000000102df555d PyRun_FileExFlags + 133
        60  org.python.python                   0x0000000102df50fa PyRun_SimpleFileExFlags + 769
        61  org.python.python                   0x0000000102e0664e Py_Main + 2970
        62  libdyld.dylib                       0x00007fff8e24d5fd start + 1

        Thread 1:
        0   libsystem_kernel.dylib              0x00007fff957c0716 __psynch_cvwait + 10
        1   libsystem_pthread.dylib             0x00007fff92e54c3b _pthread_cond_wait + 727
        2   org.python.python                   0x0000000102e0487b PyThread_acquire_lock + 135
        3   org.python.python                   0x0000000102e07f8a lock_PyThread_acquire_lock + 71
        4   org.python.python                   0x0000000102dd7c4b PyEval_EvalFrameEx + 7751
        5   org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        6   org.python.python                   0x0000000102ddc338 fast_function + 295
        7   org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        8   org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        9   org.python.python                   0x0000000102ddc338 fast_function + 295
        10  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        11  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        12  org.python.python                   0x0000000102d7a91f function_call + 349
        13  org.python.python                   0x0000000102d5c9ef PyObject_Call + 99
        14  org.python.python                   0x0000000102dd8ae9 PyEval_EvalFrameEx + 11493
        15  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        16  org.python.python                   0x0000000102ddc338 fast_function + 295
        17  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        18  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        19  org.python.python                   0x0000000102ddc338 fast_function + 295
        20  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        21  org.python.python                   0x0000000102ddc2d1 fast_function + 192
        22  org.python.python                   0x0000000102dd8de5 PyEval_EvalFrameEx + 12257
        23  org.python.python                   0x0000000102dd5c73 PyEval_EvalCodeEx + 1608
        24  org.python.python                   0x0000000102d7a91f function_call + 349
        25  org.python.python                   0x0000000102d5c9ef PyObject_Call + 99
        26  org.python.python                   0x0000000102d6774b instancemethod_call + 174
        27  org.python.python                   0x0000000102d5c9ef PyObject_Call + 99
        28  org.python.python                   0x0000000102ddba77 PyEval_CallObjectWithKeywords + 93
        29  org.python.python                   0x0000000102e083d3 t_bootstrap + 70
        30  libsystem_pthread.dylib             0x00007fff92e52899 _pthread_body + 138
        31  libsystem_pthread.dylib             0x00007fff92e5272a _pthread_start + 137
        32  libsystem_pthread.dylib             0x00007fff92e56fc9 thread_start + 13

        Thread 0 crashed with X86 Thread State (64-bit):
          rax: 0x00000001061a22a8  rbx: 0x0000000000000000  rcx: 0x7a0054b7108ed714  rdx: 0x0000000000000000
          rdi: 0x0000000000000000  rsi: 0x0000000106136cab  rbp: 0x00007fff5ceb12b0  rsp: 0x00007fff5ceb12a8
           r8: 0x0000000000000006   r9: 0x00007ff0d3c00000  r10: 0x2000000000000200  r11: 0x00000000000ba439
          r12: 0x0000000103f85684  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000102e7d138
          rip: 0x0000000000000000  rfl: 0x0000000000010206  cr2: 0x0000000000000000

        Logical CPU:     2
        Error Code:      0x00000014
        Trap Number:     14

**Comment by venius** [comment]
I use the frida module in python shell,but encounter an segment fault:
$ python
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>> i
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'i' is not defined
>>> session = frida.get_remote_device().attach("com.android.browser")
Segmentation fault: 11

I use this command to dynamic link the python,but it dosen't work:
install_name_tool -change /System/Library/Frameworks/Python.framework/Versions/2
.7/Python /Library/Frameworks/Python.framework/Versions/2.7/Python _frida.so

and I also encounter another problem,when i execute this command,it failed to attach the target process:
$ frida-trace -R -i open com.android.browser
Failed to attach: Could not connect to 127.0.0.1: Connection refused

I guess it's the same problem with @fabianfreyer ,any advices?

**Comment by oleavr** [comment]
@venius Hi,

There are two different issues here (none of them relevant to this issue, but still, you found a bug!):

1) This is a bug where your line containing just "i' raises an exception and causes the Python interpreter to shut down, which in turn shuts down Frida, and triggers a bug where it crashes when shut down just after initializing it. Very interesting. I'll investigate this.

2) This looks like you either didn't `adb forward` the relevant ports (see docs), or `frida-server` is not running on your device. Could you please verify what the issue is?

Cheers!

**Comment by venius** [comment]
@oleavr ,the second problem has nothing to do with "i",it just an input mistake!
$ Python
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>> session = frida.get_remote_device().attach("com.android.browser")
Segmentation fault: 11

I think it's the same problem with@fabianfreyer,I use "install_name_tool -change" to change the path of python,it works one time for " frida-trace -R -i open com.android.browser",but the second time ,it failed again,and raise an error:Failed to attach: Could not connect to 127.0.0.1: Connection refused.Before this,i had use adb forward to the relevant ports!And frida-server is running on my device!

**Comment by oleavr** [comment]
Ahh sorry, I misunderstood, I thought the input mistake accidentally triggered a bug, and not the import itself. :)

Hmm, did you forward enough of the ports? 27042 is the base port used for enumerating processes etc., and then you need to forward the next ports depending on how many parallel sessions you end up with. Did you try forwarding 27042 through 27049 for example?

Cheers!

**Comment by oleavr** [comment]
This issue has been fixed.
