### ISSUE TITLE
how to attach process use pid in attaching usb process

### ISSUE THREAD

**Issue by 3xp10it** [frida/frida-python#130]
I try to use frida-python to attach a ios usb process,but the process name is not recgnized like below:
```
✗ tmp frida-ps -U 
PID  Name 
----  ------------------------------- 
1253 Cydia 
1467  InCallService 
1373  MessagesNotificationViewService 
1514  ä»æ¤´æ¡ 
1370  ä¿¡æ¯ 
1448  º§çµ½± 
1349  ¹³®è¯
```

How can I attach the process with pid=1514 while I am using python api to call frida?

**Comment by oleavr** [comment]
Hi,

You can use `frida.attach(1349)` or `device.attach(1349)` to attach to PID 1349, instead of passing a string to match on the process name.

Cheers!
