### ISSUE TITLE
can I debug frida script?

### ISSUE THREAD

**Issue by Youlor** [frida/frida-python#134]
how can I debug the js script in frida? Thanks!

**Comment by ChiChou** [comment]
frida now uses Duktape, it is said that it supports debugging (haven't try it)

**Comment by 4val0v** [comment]
Also interested in this question

**Comment by oleavr** [comment]
Switch to the V8 runtime (`--runtime=v8`) and add `--debug`, then fire up Chrome's Inspector.

**Comment by didi789** [comment]
Can you explain more about the flags? (--runtime=v8 and add --debug)
How can I use them?

**Comment by oleavr** [comment]
@didi789 For example `frida -p 0 --runtime=v8 --debug`, then open Chrome's Inspector and click on the green Node.js icon near the top left corner. That's it.

**Comment by oleavr** [comment]
(At the API level pass `runtime=v8` to `create_script()`, and use `session.enable_debugger()` to enable the debugger.)

**Comment by MedAmine121** [comment]
> (At the API level pass `runtime=v8` to `session.create_script()`, and use `session.enable_debugger()` to enable the debugger.)
Seems like sesssion.enable_debugger() has been moved to script.enable_debugger()
