### ISSUE TITLE
prompt-toolkit library upgrade breaks frida repl on new installations

### ISSUE THREAD

**Issue by Hamz-a** [frida/frida-python#137]
The [prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) library which the frida repl relies on has been upgraded to V2.

When installing frida, the v2 version gets installed via pip. However this breaks the repl and makes it unusable:

```
frida -U SampleApp
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/frida", line 11, in <module>
    load_entry_point('frida==11.0.5', 'console_scripts', 'frida')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/frida/repl.py", line 15, in main
    from prompt_toolkit.shortcuts import create_prompt_application, create_output, create_eventloop
ImportError: cannot import name 'create_prompt_application'
```

Debugging further it seems that the prompt-toolkit API has drastically changed their API. So there are two solutions imho:
1. Rewrite the whole repl conforming to the V2 API of prompt_toolkit
2. Quick fix: edit [setup.py](https://github.com/frida/frida-python/blob/master/src/setup.py#L145) to introduce a max version in the install requirements

Before:
```
    install_requires=[
        "colorama >= 0.2.7",
        "prompt-toolkit >= 0.57",
        "pygments >= 2.0.2"
    ],
```

After:
```
    install_requires=[
        "colorama >= 0.2.7",
        "prompt-toolkit >= 0.57, <2.0",
        "pygments >= 2.0.2"
    ],
```

Ideas what's best?

**Comment by oleavr** [comment]
Thanks for reporting. The quick fix approach has been implemented in 11.0.6, released today. PRs welcome to upgrade frida-python to the new API, though!
