### ISSUE TITLE
Setup: Provide an argument to use pypi mirror

### ISSUE THREAD

**Issue by ChiChou** [frida/frida-python#141]
Currently `index-url` is hardcoded in:
https://github.com/frida/frida-python/blob/86e52547a6c5702507b4e9323edd3195bb9fce80/src/setup.py#L80

It's painful when the pypi site is blocked under certain circumstances.

**Comment by Manouchehri** [comment]
Ran into this issue as well, would be nice if to use the user’s index-url (defined in /etc/pip.conf or ~/.pip/config).

**Comment by GalaxySnail** [comment]
Surprisingly it is still not solved now. I think `pip config get global.index-url` and [PEP 503](https://www.python.org/dev/peps/pep-0503/) will be helpful.

**Comment by oleavr** [comment]
@GalaxySnail Did I just hear you volunteering to submit a PR? ;)

**Comment by GalaxySnail** [comment]
I'm not sure, but I can have a try. ;)
But in my opinion, it is better to distribute wheels instead of eggs if possible.

**Comment by nblog** [comment]
> Surprisingly it is still not solved now. I think `pip config get global.index-url` and [PEP 503](https://www.python.org/dev/peps/pep-0503/) will be helpful.

should `pip config get global.extra-index-url` be checked first?

**Comment by GalaxySnail** [comment]
> [extra-index-url](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url)
> considering that the mirror is not complete, and pypi and other are needed.
> 
> should `pip config get global.extra-index-url` be checked first?

Thanks for reminding! But I'm not sure about the priority order, see [this question](https://stackoverflow.com/questions/67253141/python-pip-priority-order-with-index-url-and-extra-index-url) and [this issue](https://github.com/pypa/pip/issues/5045).

Are there any actual use cases?

**Comment by nblog** [comment]
> > [extra-index-url](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url)
> > considering that the mirror is not complete, and pypi and other are needed.
> > should `pip config get global.extra-index-url` be checked first?
> 
> Thanks for reminding! But I'm not sure about the priority order, see [this question](https://stackoverflow.com/questions/67253141/python-pip-priority-order-with-index-url-and-extra-index-url) and [this issue](https://github.com/pypa/pip/issues/5045).
> 
> Are there any actual use cases?

i think there is no priority, it's just that some people may not use "global.index-url", because of the difference in information. 
it may be a default scheme, such as `pip config get global.index-url` does not exist.

![image](https://user-images.githubusercontent.com/10218627/141057647-37812f4a-23f1-4252-99c0-f8066ceb1b71.png)

**Comment by GalaxySnail** [comment]
> i think there is no priority, it's just that some people may not use "global.index-url", because of the difference in information. it may be a default scheme, such as `pip config get global.index-url` does not exist.
> 
> ![image](https://user-images.githubusercontent.com/10218627/141057647-37812f4a-23f1-4252-99c0-f8066ceb1b71.png)

OK, got it.

Which of `index-url` and `extra-index-url` should be checked first? I think it may be better to check `index-url` first, and check `extra-index-url` when `index-url` doesn't exist.

**Comment by nblog** [comment]
> > i think there is no priority, it's just that some people may not use "global.index-url", because of the difference in information. it may be a default scheme, such as `pip config get global.index-url` does not exist.
> > ![image](https://user-images.githubusercontent.com/10218627/141057647-37812f4a-23f1-4252-99c0-f8066ceb1b71.png)
> 
> OK, got it.
> 
> Which of `index-url` and `extra-index-url` should be checked first? I think it may be better to check `index-url` first, and check `extra-index-url` when `index-url` doesn't exist.

agreed. thanks for u contribution.
