### ISSUE TITLE
Unstable early hooking

### ISSUE THREAD

**Issue by H4oK3** [frida/frida-python#143]
I have some python code like this:

~~~PYTHON
# the app not started yet
pid = device.spawn([packagename])
process = device.attach(pid)

script = process.create_script(script_to_load)
script.on('message',onMessage)
script.load()

device.resume(pid)
~~~

and the `script_to_load` was just sth like this:

~~~JAVASCRIPT
setTimeout(function() {
    Java.perform(function() {
        console.log("Script loaded..")
        // does not do much
    });
}, 0);
~~~

But looks like this implementation is not stable, i.e. if the spawning app takes couple seconds to launch(it happens), then that script would be lost and `perform` was never executed.

**Comment by oleavr** [comment]
Does your Python script exit right after calling `resume()`? If so, that's the problem – the Python side will undo everything before exiting. Also, you definitely want to remove that `setTimeout()` -- it means you break early instrumentation as your instrumentation code may run after the app has started executing its own code.

**Comment by H4oK3** [comment]
Thanks man, that helps; I removed setTimeout() and now it works!
