### ISSUE TITLE
Unable to execute frida on JB iOS 11.2.5 with python3.7.1

### ISSUE THREAD

**Issue by Zatyam** [frida/frida-python#149]
**After installing frida and frida-tools through pip3 on my iOS 11.2.5 device when I execute 'frida', it says the following. I even tried uninstalling and reinstalling them, but the issue persists**

root# frida

***
Failed to load the Frida native extension: dlopen(/usr/local/lib/python3.7/site-packages/_frida.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
        /usr/local/lib/python3.7/site-packages/_frida.cpython-37m-darwin.so: no matching architecture in universal wrapper
        /usr/local/lib/python3.7/site-packages/_frida.cpython-37m-darwin.so: no matching architecture in universal wrapper
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "/usr/local/bin/frida", line 11, in <module>
    load_entry_point('frida-tools==1.3.2', 'console_scripts', 'frida')()
  File "/usr/local/lib/python3.7/site-packages/frida_tools/repl.py", line 22, in main
    import frida
  File "/usr/local/lib/python3.7/site-packages/frida/__init__.py", line 24, in <module>
    raise ex
  File "/usr/local/lib/python3.7/site-packages/frida/__init__.py", line 7, in <module>
    import _frida
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/_frida.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
        /usr/local/lib/python3.7/site-packages/_frida.cpython-37m-darwin.so: no matching architecture in universal wrapper
        /usr/local/lib/python3.7/site-packages/_frida.cpython-37m-darwin.so: no matching architecture in universal wrapper

**Comment by doc-sewell-alpine** [comment]
I am having this same issue.  How did you fix it?
