### ISSUE TITLE
Accessing ArrayBuffers crashes the target process

### ISSUE THREAD

**Issue by sorgloomer** [frida/frida-python#15]
Hi there,

Running a javascript code which tries to access an ArrayBuffer object crashes the target process. Either instantiating one (```new ArrayBuffer(16)```) or obtaining it from a typed array (```(new Uint8Array(16)).buffer```). The strange thing is that typed arrays work fine.

I was trying it on win8.1 x64, injected into notepad.exe using the python module.

```
  Problem Event Name:	BEX64
  Application Name:	notepad.exe
  Application Version:	6.3.9600.16384
  Application Timestamp:	5215ef3b
  Fault Module Name:	StackHash_8b8a
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	PCH_84_FROM_frida_agent_64+0x0000000000126901
  Exception Code:	c0000005
  Exception Data:	0000000000000008
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	1038
  Additional Information 1:	8b8a
  Additional Information 2:	8b8a2fde42fa3a121f9287ec033c5915
  Additional Information 3:	c366
  Additional Information 4:	c366b210ce5036fb8c4f3db6cc497a4f
```

Keep up the awesome work!

**Comment by oleavr** [comment]
Interesting. It sounds like a bug in the version of V8 used by Frida. Should be resolved on the next upgrade hopefully :)

**Comment by oleavr** [comment]
I recently upgraded V8, and just verified that this is still an issue. Turns out my assumption was wrong, and this was just a matter of us providing V8 with an array buffer allocator. This is now part of latest code in git, and will make into the upcoming 4.0.0 release.

Thanks for reporting!
