### ISSUE TITLE
missing python 2.7 686 binary

### ISSUE THREAD

**Issue by blshkv** [frida/frida-python#151]
https://pypi.org/project/frida/#files
I noticed that the latest 12.5.7 is missing python 2.7 on i686 platform.
Could you check a build script and generate it please?

Thank you

**Comment by oleavr** [comment]
Oops, nice catch.

<img width="784" alt="Screenshot 2019-05-22 at 02 43 16" src="https://user-images.githubusercontent.com/735197/58139589-a7b3bd80-7c3b-11e9-95dd-73e5e77dd072.png">

Should be fixed now.
