### ISSUE TITLE
How do I use frida -H  host.....？

### ISSUE THREAD

**Issue by Ha2ryZhang** [frida/frida-python#169]
How do I use frida -H  host.....？

connect to remote frida-server on HOST

**Comment by DXCyber409** [comment]
frida.get_remote_device() sounds like possible, but I didn't figure out what's the param to pass.

**Comment by Ha2ryZhang** [comment]
> frida.get_remote_device() sounds like possible, but I didn't figure out what's the param to pass.
the param need  **ip**+**port**  
eg:
`process = frida.get_device_manager().add_remote_device("192.168.1.12:2703").attach("package name")`

and you need to disable the android firewall to access the remote connection
