### ISSUE TITLE
AttributeError: module '_frida' has no attribute 'Cancellable' 

### ISSUE THREAD

**Issue by Times125** [frida/frida-python#170]
system version: macos 10.15.6
python version: 3.8
frida version:frida-12.11.3-py3.8-macosx-10.9-x86_64
desc: when i import module firda, AttributeErrors happened: AttributeError: module '_frida' has no attribute 'Cancellable' .

**Comment by oleavr** [comment]
Your Python installation has leftovers from a previous version. Check `sys.path` and inspect each directory carefully.
