### ISSUE TITLE
Improve repl

### ISSUE THREAD

**Issue by Tyilo** [frida/frida-python#19]
Suggestions:

- [x] Ctrl-c to clear current input in prompt, instead of raising the `KeyboardInterrupt` exception (same as normal shells)
- [x] Tab auto-complete, especially for the JavaScript API (`Memory.<TAB>` should list all functions located in the `Memory` object) (implemented by @Fitblip)
- [x] Syntax coloring (Maybe steal this from cycript)
- [x] Persistent history

**Comment by oleavr** [comment]
Great ideas! Feel like having a go at it? :)

**Comment by Fitblip** [comment]
Hey @Tyilo! I've been working a bit on frida-repl tonight (mostly trying to figure out a way to do bullet two, as well as some better prompt), just figured I'd give you a heads up in case you're working on it too. Don't want to duplicate effort :+1:

**Comment by Tyilo** [comment]
These have all been implemented since moving from readline to python-prompt-toolkit.

**Comment by oleavr** [comment]
Awesome work! :muscle:
