### ISSUE TITLE
how add host instead usb to my script 

### ISSUE THREAD

**Issue by a-gamer** [frida/frida-python#226]
i make script  but it's  only work with usb frida.get_usb_device
how make it take host and port to work with them instead of usb

**Comment by oleavr** [comment]
```py
device = frida.add_remote_device("host:port")
```

or

```py
device = frida.add_remote_device("host")
```

to use the default port of 27042.

**Comment by oleavr** [comment]
(This is what frida-tools CLI tools do when you specify `-H host:port`.)
