### ISSUE TITLE
Segment fault when running frida-trace on MacOSX 10.9.5

### ISSUE THREAD

**Issue by baronpan** [frida/frida-python#26]
I cloned the code today, when running frida-trace, it makes a segment fault. Then i print logs on all the methods, finally find the crash method:

in `frida-python/src/_frida.c PySession_create_script`
When called `PyArg_ParseTupleAndKeywords` , the `name` returned null. Then when called `frida_session_create_script_sync` it crashed.

command is `./build/frida-mac-x86_64/bin/frida-trace -R com.android.chrome`, print log:

Resolving functions...                                                  

(process:31543): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
Segmentation fault: 11

**Comment by oleavr** [comment]
Sorry about this, there's some major changes happening in master right now. Hoping to stabilize things later today. I'll keep you posted.

**Comment by oleavr** [comment]
This is now fixed in git. (Remember to `git submodule update` after pulling.) Please let me know how it works for you.

**Comment by baronpan** [comment]
it runs now, thanks.
