### ISSUE TITLE
Package into wheels for pip

### ISSUE THREAD

**Issue by techtonik** [frida/frida-python#38]
`pip` is de-facto official standard for installing packages, and it is unable to install `frida`.
```
>pip install frida
Collecting frida
  Could not find a version that satisfies the requirement frida (from versions: )
No matching distribution found for frida
```

Is it possible to pack it as http://pythonwheels.com/ ?

**Comment by techtonik** [comment]
https://packaging.python.org/en/latest/pip_easy_install.html

**Comment by techtonik** [comment]
https://packaging.python.org/en/latest/distributing.html#platform-wheels
```
python setup.py bdist_wheel
```

**Comment by oleavr** [comment]
Pip is now able to install Frida. (We did not go for wheels as they don't support binary packages for Linux OSes.)

**Comment by techtonik** [comment]
Not able to test right now, but that's nice to know. =)

**Comment by paulnaoki** [comment]
installed frida with pip on windows, but when import it in python, it says:
Failed to load the Frida native extension: DLL load failed: couldn't find target module....
Please ensure that the extension was compiled for Python 3.x.

please help!!!!
