### ISSUE TITLE
Screenshot of application window in background

### ISSUE THREAD

**Issue by techtonik** [frida/frida-python#39]
I wonder if it is possible to inject into DirectX application window and grab pixels from it using frida?

https://stackoverflow.com/questions/30694056/make-screenshot-of-directx-window-that-is-hidden-and-doesnt-have-focus

**Comment by oleavr** [comment]
Yes it's definitely possible. All you need to do is find the API calls you need, and call them using `new NativeFunction(...)`. This would be an awesome tutorial if you feel like writing one up.

**Comment by techtonik** [comment]
Yes. That would be interesting, but I still don't understand how Frida works and which API calls I need. =)

**Comment by techtonik** [comment]
For now I need to figure out if window is being painted by DirectX.

**Comment by oleavr** [comment]
:+1: Hopefully the docs at www.frida.re should be decent, but let me know if you have any questions.
