### ISSUE TITLE
Running repl in PyCharm console

### ISSUE THREAD

**Issue by marc1006** [frida/frida-python#41]
I got the error 
`lib/python3.4/site-packages/prompt_toolkit/terminal/vt100_input.py", line 333, in __init__
    self.attrs_before = termios.tcgetattr(fileno)
termios.error: (25, 'Inappropriate ioctl for device')`

My current solution for it is to use http://blog.jetbrains.com/pycharm/2010/12/python-remote-debug-with-pycharm/

**Comment by oleavr** [comment]
PRs appreciated :)
