### ISSUE TITLE
How to print the registers

### ISSUE THREAD

**Issue by acgmohu** [frida/frida-python#49]
HI gays,

I try to print the reigisters from r0 to r15.using the Memory.scan, but ...

```
Module.enumerateExports(('libc.so', { 
...
onEnter: function(args) {
         //  I want to match anything.
        Memory.scan(args[0], 16, "%(*)", {...}); // Error: invalid match pattern,
},
onLeave: function(retval) {
}
...
```

Thanks.

**Comment by oleavr** [comment]
Hi,

`Memory.scan()` is for finding patterns in memory, not for printing registers. From `onEnter` you can use `this.context.r0` to read the `r0` register.

Cheers!

**Comment by acgmohu** [comment]
Hi obleavr,
Thanks very much :). I will try it again.
Maybe I need to read the source code about this. I had read the `frida/core.py` and `frida/tracer.py` and found that they do not cover all the javascript api. Any advise?

**Comment by oleavr** [comment]
The JavaScript API is documented here:
http://www.frida.re/docs/javascript-api/

**Comment by acgmohu** [comment]
Thanks.
I did not notice the `Thread` API. :-( My faults.
