### ISSUE TITLE
About anti-debug

### ISSUE THREAD

**Issue by acgmohu** [frida/frida-python#50]
Hi,
In Android, one sample has anti-debug code.  When my script attach the process, it will like this:
```
Traceback (most recent call last):
  File "crack3.py", line 10, in <module>
    session = frida.get_usb_device().attach("test.crackme")
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frida-5.0.2-py3.4-macosx-10.10-x86_64.egg/frida/core.py", line 87, in attach
frida.PermissionDeniedError: unable to access process with pid 4973 due to system restrictions; try `sudo sysctl kernel.yama.ptrace_scope=0`, or run Frida as root
```
```
```
root      8296  1     24724  20308 ffffffff 00000000 S ./frida-server
root      8378  8296  4760   1168  ffffffff 00000000 S /data/local/tmp/.frida-60bfdeca9cc8aef9bbd115a03efb8377/frida-helper-32
```
```

I try to hook its father process zygote, but this will crash other applications.
```
 Module.enumerateExports("libdvm.so", {                
      onMatch: function(e) {                            
          if(e.type == 'function') {                    
              if(e.name == "_Z12dexFileParsePKhji") {
                  send(e.name);                         
                  Interceptor.attach(e.address, {       
                      onEnter: function(args) {         
                          send("enter");                
                      },                                
                      onLeave: function(retval){        
                          send("leave");                
                      }                                 
                  });                                                                   
              }                                         
          }                                             
      },                                                
      onComplete: function() {}                         
  });                                                   
```         

So I try to attach its children pid( /proc/_pid/task ), but I have not found the API.

Any idea?

**Comment by oleavr** [comment]
Hi,

Interesting problem. I think longer term Frida should support other injection strategies on Linux/Android by using a kernel driver as a fallback strategy. Until then I think you're limited to `spawn([package_name])` (or `enable_spawn_gating()` to hook all processes spawned by zygote), that way there's no need to use ptrace at all.

Cheers!

**Comment by oleavr** [comment]
For spawn-gating examples, see:
https://gist.github.com/oleavr/ae7bcbbb9179852a4731

**Comment by acgmohu** [comment]
THS. Now I can attach the process, and another problem rose. 

```
Traceback (most recent call last):
  File "./crack3.py", line 83, in <module>
    script.exports.init()
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frida-5.0.2-py3.4-macosx-10.10-x86_64.egg/frida/core.py", line 533, in method
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frida-5.0.2-py3.4-macosx-10.10-x86_64.egg/frida/core.py", line 484, in _rpc_request
Exception: Unable to find method 'init'
```

**Comment by oleavr** [comment]
It's because you don't export any `init` function from your script, like in the example:

```
rpc.exports = {
    init() {

**Comment by oleavr** [comment]
That's just an example though.. but it's an easy way of making sure that your script has instrumented all the necessary APIs before the host side calls `.resume()` to let the main thread start executing `main()`.

**Comment by acgmohu** [comment]
Oh, I got it! Thanks.

**Comment by acgmohu** [comment]
Hi oleavr, 
I want to hook the apk's libs(.so), but it's not in the enumerate_modules.  I can find the so in the /proc/pid/maps. 
```
       s = device.attach(spawn.pid)           
      modules = s.enumerate_modules()
      module = None
         for m in modules : 
              if "/system" not in m.path:
                  print(m.name) // not found /data/app-lib/...
```

**Comment by oleavr** [comment]
If `enumerate_modules()` doesn't see it then that means that you're checking too early (it parses `/proc/pid/maps` to deliver you those results every time you call it). You can hook `dlopen()` and instrument it in `onLeave` when you detect it's the .so you're interested in.

Regarding `spawn()` not working, could you show me the code you're trying with?

**Comment by acgmohu** [comment]
You can read it in here :
https://github.com/acgmohu/AliMSC/tree/master/AliMSC_1st/AliCrackme_3

**Comment by oleavr** [comment]
Unfortunately I can't see anything obvious wrong, are you certain that it's the right process being instrumented? (With spawn gating you have to manually launch the app. It is designed to let you handle apps spawned out of your control, like companion services bundled with the app, so it is recommended that you `.spawn()` the app itself.)

**Comment by acgmohu** [comment]
Yes, I manually run the app. 
Now I update the code and test again.  
And found `session.enumerate_modules()` and `Dalvik.enumerateLoadedClasses` can not work. -_-|||

```
Waiting for data
Instrumenting: Spawn(pid=12413, identifier="crackme.a3")

APK Libs :
/data/local/tmp/.frida-e7b5b1d0cfee2e0cdea4407a5d58379f/frida-loader-32.so
/data/local/tmp/.frida-e7b5b1d0cfee2e0cdea4407a5d58379f/frida-agent-32.so

APK Classes:

Resume: Spawn(pid=12413, identifier="crackme.a3")
Waiting for data
```

The code is [here](https://github.com/acgmohu/AliMSC/blob/master/AliMSC_1st/AliCrackme_3/crack3.py).

**Comment by oleavr** [comment]
Ah I see what the problem is. The code you're executing is running before the app has started launching, which gives you a chance to instrument APIs that the app will be calling very early on. When you call `.resume()` it will start executing, and it's after that point that the app will load JNI libraries. That's why you need to hook the appropriate APIs so you can instrument the JNI libraries just after they've been loaded, but before the app has a chance to call any functions in them.

**Comment by acgmohu** [comment]
Yes! You are right! Thanks Very Much!!!

**Comment by oleavr** [comment]
:+1:
