### ISSUE TITLE
frida-trace man page lookup is broken

### ISSUE THREAD

**Issue by 0xABD** [frida/frida-python#62]
The man page lookup seems to be broken due to regex issue at https://github.com/frida/frida-python/blob/master/src/frida/tracer.py#L1286
```
match = re.search(r"^SYNOPSIS(?:.|\n)*?((?:^.+$\n)* {5}" + function.name + r"\(.*\n(^.+$\n)*)(?:.|\n)*^DESCRIPTION", output.decode('UTF-8', errors='replace'), re.MULTILINE)
```
1. The regex does not take into account that the target function we are looking for has a return value, e.g. `int open(const char *pathname, int flags);` 
and that the offset may not be exactly {5} spaces, but e.g. 7 spaces on Linux.
2. The regex collects several lines with the target function, e.g. for `open`, if corrected for issue 1), it will be 
```
      int open(const char *pathname, int flags);
        int open(const char *pathname, int flags, mode_t mode);
```
and then the regex also collects all their parameters together, so the result will contain 5 parameters instead of 2 or 3.

**Comment by oleavr** [comment]
Thanks for tracking down these bugs! Feel like cooking up a patch? 😊

**Comment by 0xABD** [comment]
The proposed pull request https://github.com/frida/frida-python/pull/63 should take the first match on a function prototype:
* if defined on one line, like `int open(const char *pathname, int flags);`
* if defined with varargs, like `int ioctl(int d, unsigned long request, ...);`
* if defined on multiple lines, like 
```
      void *mmap(void *addr, size_t length, int prot, int flags,
              int fd, off_t offset);
```
* and also when the return type is a pointer of arbitrary depth, like `*mmap`

**Comment by oleavr** [comment]
PR merged, thanks!
