### ISSUE TITLE
get_remote_device() returns wrong device

### ISSUE THREAD

**Issue by jgrover** [frida/frida-python#73]
I'm currently running Frida 7.0.11 on Mac OS X (el capitan). Frida was installed successfully using pip.

When attempting to attach to my jailbroken & frida-enabled iOS device that is plugged in via USB, the `get_remote_device()` python function returns the wrong device. It currently returns the `Device(id="tcp", name="Local TCP", type="remote")` device object -- NOT the correct`Device(id="xxxx", name="iPhone", type='tether')` object.

I guess it's only looking at the "remote" type, but in my case, the remote device is actually the tethered device so it's a bit of a misnomer.

**Comment by oleavr** [comment]
Thanks for reporting. The `remote` device is really meant for remote (TCP). You want to use `frida.get_usb_device()` instead.

Cheers!
