### ISSUE TITLE
discover doesn't attach to a single thread

### ISSUE THREAD

**Issue by manuporto** [frida/frida-python#74]
When using `frida-discover` with an Android phone I'm not able to trace a single thread on any app that I tested it. For example:

```
$ frida-discover -U com.android.email
Tracing 0 threads. Press ENTER to stop.
```

Apps that I attempted to trace:
- com.android.chrome
- com.android.systemui
- com.android.email

Probably it's my mistake because I'm not sure that I'm using the tool right. If that's the case, please refer me to an usage example because I couldn't find any.

Cheers!

---

**OS**: Ubuntu 14.04 x86
**Frida**: 7.0.10
**Android**: 4.3

**Comment by daniula** [comment]
Same for me running OSX, newest Frida and Android 6.0.1.
I used both `frida-discover -U -n` and `frida-discover -U -p` options.

**Comment by daniula** [comment]
@manuporto Maybe this will be helpful for you: I've tried to overcome this issue by running `frida-trace -U -i "*"`.

**Comment by manuporto** [comment]
@daniula yes that's a workaround I guess, although when doing that I experienced some random "crashes". Not actual crashes, but the terminal became unresponsive and I had to directly kill the process.

I will try again and post here if I have any news.

**Comment by Silur** [comment]
same for me on archlinux x86_64

**Comment by oleavr** [comment]
The Stalker API is only implemented on x86 for now, and hasn't had a lot of testing on Linux. Please file specific issues in [frida-gum](https://github.com/frida/frida-gum). Cheers!
