### ISSUE TITLE
frida-trace code is not auto reloading with given commands on quickstart page

### ISSUE THREAD

**Issue by daniula** [frida/frida-python#75]
Following steps from quickstart it seems that code is not reloading. Every time I want to run new javascript code I have to kill `frida-trace` restart Twitter app on my device and then launch `frida-trace` back again.

**Comment by oleavr** [comment]
Which OS/kernel is this on?

**Comment by daniula** [comment]
OSX / Darwin Kernel Version 15.4.0

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
