### ISSUE TITLE
Support for multi-module javascript files.

### ISSUE THREAD

**Issue by ali-alidoust** [frida/frida-python#76]
It is not currently possible to import/require another .js file.

**Comment by oleavr** [comment]
This is already possible by using `frida-compile`:
https://www.npmjs.com/package/frida-compile

Built-in support for this would add too much complexity and still wouldn't solve the lack of ES6 features in the Duktape runtime. The aforementioned frida-compile tool solves both of these problems, while keeping things simple in Frida.
