### ISSUE TITLE
How to hook a java function when the function is leaving?

### ISSUE THREAD

**Issue by cx9527** [frida/frida-python#79]
How to hook a java function when the function is leaving? Like "OnEnter" and "OnLeave"

**Comment by oleavr** [comment]
Java functions are hooked by assigning to the `implementation` property. That means you are responsible for calling the original implementation, if you want that. onLeave is then just whatever code you decide to add after the call to the original implementation. Have a look at the `Java.perform()` documentation for an example:
http://www.frida.re/docs/javascript-api/#java

**Comment by cx9527** [comment]
OK!I see,thank you for that
