### ISSUE TITLE
Cannot see or attach several processes on Windows

### ISSUE THREAD

**Issue by tfoldi** [frida/frida-python#81]
When I run `frida` or `frida-ps` on processes that are executed from windows services, it throws different errors.

I do not see all processes even if execute `frida-ps` from an Administrator cmd shell:

![image](https://cloud.githubusercontent.com/assets/82426/15456284/a48942b2-206b-11e6-8e21-800530babd8a.png)

Also, when I try to access the process by pid (as `frida` repl does not find these by name) I have two scenarios - both are executed from administrator cmd.exe:

  * If the username is the same as process that are running as service (staradmin), then: `Failed to attach: unexpected error while attaching to process with pid 2340 (OpenProcess returned 0x00000005)`
  * If I try it with local administrator `Failed to attach: unexpected error while attaching to process with pid 6832 (RtlCreateUserThread returned 0xc0000022)` 

The first screenshot shows first scenario. UAC turned off, OS is:

    OS Name:                   Microsoft Windows Server 2012 R2 Datacenter 
    OS Version:                6.3.9600 N/A Build 9600

Please advise, what can I do to make this work?

**Comment by tfoldi** [comment]
aaaa, maybe my python is 32bit :( let me check, if yes, I will close this :(

**Comment by tfoldi** [comment]
that was it

**Comment by mbevilacqua** [comment]
Same thing here, confirmed python 64b, hello64.exe test compiled with mingw64. frida-ps not seeing the process on 64b Win10 VM.
