### ISSUE TITLE
Frida Eventually Crashes In Infinite Loop

### ISSUE THREAD

**Issue by QewQew** [frida/frida-python#84]
I have an infinite loop running to check if an attach is successful (essentially, looping until the process exists):

```
    session = None
    while session is None:
        try:
            session = frida.attach(pid)
        except frida.ProcessNotFoundError:
            pass
```

However, the interpreter eventually crashes.
Is there any other way to check if a process exists using frida?

**Comment by oleavr** [comment]
Fixed in latest Frida 9.x.
