### ISSUE TITLE
Frida wont run in a celery task

### ISSUE THREAD

**Issue by ChillarAnand** [frida/frida-python#86]
``` sh
→ frida-ls-devices
Id                                    Type    Name           
------------------------------------  ------  ---------------
local                                 local   Local System   
BFA1B60A-DC7D-4F67-8DB5-78FEF6CAEA80  tether  Motorola XT1022
tcp                                   remote  Local TCP   
```

Consider this simple task

``` py
@app.task
def get_frida_device(serial_number):
    print('getting device')
    import frida
    d = frida.get_device(serial_number)
    print('got {}'.format(d))
```

When running as function `get_frida_device('BFA1B60A-DC7D-4F67-8DB5-78FEF6CAEA80')` everything works fine. However when it is queued, it hangs at `frida.get_device` and never prints last line.

**Comment by ChillarAnand** [comment]
I raised an issue on celery. Celery author replied saying that issue is not celery and may be [frida is not fork safe](https://github.com/celery/celery/issues/3447#issuecomment-247292622)? Can some one confirm this?

**Comment by oleavr** [comment]
Yes, I'm afraid we won't solve this in the short-term. (PRs welcome though!)

**Comment by gil01karougbe** [comment]
does this issue exists in curent versions?

**Comment by iteroji** [comment]
> does this issue exists in current versions?

I believe it's still the case. The celery task will hang indefinitely upon hitting the first Frida line. Changing the Celery pool type to threads appears to work, but it might just open an another can of worms.
