### ISSUE TITLE
[help]how-to log output when in Preloaded mode

### ISSUE THREAD

**Issue by horsegitted** [frida/frida-python#91]
Hi there,

I'm trying in Preloaded mode, hook.js runs ok. The tool is really powerful.
But I don't know how to redirect the  console.log to file or other place, what I want is to hook one process and all its child process, so choose Preloaded mode, use " am start -n com.xxx.example", hopelly we can get the hook log of this apk's child process ( such as it invoke some other elf or shell command using exec or other subprocess functions).

if I use  console.log, it will only output some log before start the apk, such as below:
........
{"type":"send","payload":"open(\"/proc/self/cmdline\")"}
{"type":"send","payload":"open(\"/proc/self/task/9908/attr/current\")"}
{"type":"send","payload":"open(\"/system/lib/logging.properties\")"}
{"type":"send","payload":"open(\"/system/framework/core.jar\")"}
{"type":"send","payload":"open(\"/dev/binder\")"}
{"type":"send","payload":"open(\"/dev/cpuctl/apps/tasks\")"}
{"type":"send","payload":"open(\"/dev/cpuctl/apps/bg_non_interactive/tasks\")"}
Starting: Intent { cmp=com.xxx.example/.activity.StartActivity }
root@hammerhead:/data/local/tmp #

Is there any other way to fetch all the log ouput of the process and all its child process ?
Thanks for your help!

**Comment by oleavr** [comment]
Hi,

You can use the [File](http://www.frida.re/docs/javascript-api/#file) API to build your own logging, something like:

```js

const getpid = new NativeFunction(Module.findExportByName(null, 'getpid'), 'int', []);
const logFile = new File('/data/local/tmp/frida-' + getpid() + '.log', 'w');

function log(args...) {
  logFile.write(args.join(' '));
  logFile.flush();
}
```

then instead of `console.log()`, use `log()`.

Cheers!

**Comment by oleavr** [comment]
(Fixed a couple of bugs in my example, should work now.)

**Comment by horsegitted** [comment]
Thanks a loooot! Much appreciated!
