### ISSUE TITLE
Unable to attach to processes without Apple's libc (for now)

### ISSUE THREAD

**Issue by brian-leidos** [frida/frida-python#97]
Trying to attach to iOS process from Linux using a custom script:

```
import frida
import sys
  :
otherParm = sys.argv[0];
pkg = sys.argv[1];
  :
remote = frida.get_usb_device();
  
process = remote.attach(pkg);
```
This gives error: 
Traceback (most recent call last):
  File "myscript.py", line xx, in <module>
    process = remote.attach(pkg);
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 96, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.TransportError: unable to attach to processes without Apple's libc (for now)

I'm Using Frida 8.1.10, under Ubuntu and Python 2.7. I can do frida-ps -U, but frida-trace -U "appname" gives this same "(for now)" error.

**Comment by oleavr** [comment]
Thanks for reporting, and sorry for the delay. This should be fixed in the latest Frida 9.x, please reopen if this isn't the case.

**Comment by filedescriptor** [comment]
I'm seeing the same thing in Frida 9.1.26 when I am trying to do frida-trace on a 32bit iPad mini (running iOS 6.1.2).
